### ISSUE TITLE
name attribute in test-suite and test-results element of output xml is different to nunit 2.6.4 using nunit2-format

### ISSUE THREAD

**Issue by bunnu** [nunit/nunit#1195]
I'm using nunit 3.0.1 generating output in nunit2-format.
In nunit 2.6.4 the name attribute of test-suite and test-results is the full path of the test assembly.
In nunit 3.0.1 the name attribute of test-suite is the filename of the test assembly and the name attribute of test-results is empty.

Example
```
Nunit-2.6.4\nunit-console-x86.exe "C:\test\UnitTests.dll" /runlist="C:\test\list.txt" /nologo /result="C:\test\nunit2.xml"
```
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\test\UnitTests.dll" total="1" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-01-15" time="13:42:42">
[...]
  <test-suite type="Assembly" name="C:\test\UnitTests.dll" executed="True" result="Success" success="True" time="0.504" asserts="0">
[...]
  </test-suite>
</test-results>
```

```
Nunit-3.0.1\nunit3-console.exe "C:\test\UnitTests.dll" --testlist="C:\test\list.txt" --noheader --result="C:\test\nunit3.xml";format=nunit2"
```

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="" total="1" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-01-15" time="12:32:27">
[...]
  <test-suite type="Assembly" name="UnitTests.dll" executed="True" result="Success" success="True" time="0,691" asserts="0">
[...]
  </test-suite>
</test-results>
```

**Comment by rprouse** [comment]
Thanks for the report. I am going to set this as a low priority bug since the impact doesn't seem to be large and it might be difficult to fix. If this bug impacts you in a meaningful way, let me know and I will increase the priority.

**Comment by bunnu** [comment]
I'm using opencover.ui for visualizing code coverage in Visual Studio. opencover.ui is relying on the full assembly path (in the element test-suite).
(I developed a small patch to use opencover.ui with nunit 3.0)

**Comment by CharliePoole** [comment]
I can fix this at the same time as #1189

**Comment by linquize** [comment]
But it is not fixed when using nunitlite 3.2

**Comment by CharliePoole** [comment]
Your comment is appearing in my email and not on GitHub, so I'll answer by
email. If you know that you did anything special with this comment, which
might have caused it not to appear on GH, please let me know as I've been
trying to figure out why this happens with some people's comments.

Anyway... you are quite right. The issue that was reported against the
console runner was fixed. I should have remembered to make the same fix to
NUnitLite, in case anyone needed it. I'm reopening this temporarily until I
get that fixed as well.

**Comment by CharliePoole** [comment]
PR #1497 completed this.

**Comment by maximpashuk** [comment]
I have to say that this issue is not completely fixed, if you compare xmls form @bunnu comment, there are two differences:
1. ```<test-suite name``` attribute
2. ```<test-results name``` attribute

In NUnit 3.2.1 only first one fixed, second is still appears - test-results name attribute is empty.

@CharliePoole I don't know should I create new issue on this or you will reopen this one ?

**Comment by rprouse** [comment]
On my phone, so limited search, but I am pretty sure the second was reported and fixed in 3.4 which will be out soon.

**Comment by maximpashuk** [comment]
Found an issue #1543 about that, thanks.
Wait for nunit 3.4 to resolve.
