### ISSUE TITLE
Assert.IsTrue throws NullReferenceException

### ISSUE THREAD

**Issue by ayumsoftware** [nunit/nunit#2238]
object a = null, b = null;
bool areEqual = System.Object.ReferenceEquals(a, b);

Console.WriteLine(areEqual); //prints True

//all of these asserts will throw "Object reference not set to an instance of an object."
Assert.IsTrue(areEqual);
Assert.IsTrue(a == null && b == null);
Assert.IsTrue((object)a == null && (object)b == null);

**Comment by jnm2** [comment]
Is this a dupe of https://github.com/nunit/nunit/issues/2223? Also please specify the NUnit Framework version you are using because this looks like a lot of bugs that have been fixed.

**Comment by CharliePoole** [comment]
I was so stunned by this that I had to try it out! These are all the most fundamental assertions and have worked for a long time. Still, who knows? So I wrote this, which passes everything:

```C#
        [Test]
        public void Issue2238()
        {
            object a = null, b = null;
            bool areEqual = ReferenceEquals(a, b);

            Assert.True(areEqual);

            Assert.True(a == b);
            Assert.IsTrue(a == b);
            Assert.That(a == b);
            Assert.That(a == b, Is.True);
            Assert.That(a, Is.EqualTo(b));

            Assert.Null(a);
            Assert.Null(b);
            Assert.That(a == null && b == null);
        }
```

I'm guessing that @jnm2 got it right. Are you somehow trying to use NUnit Assert outside of an NUnit test? That will not work. The assertion depends on a bunch of things that are set up when NUnit runs the test.

There was actually once a plan to split out assertions so that they might be used outside of NUnit, the judgement of the team was that it isn't worth the effort. See #502.

FWIW, I think being able to use assertions and constraints outside of NUnit would be useful. I'm planning to do that in the framework I work on after NUnit. 😸

**Comment by ayumsoftware** [comment]
I'm using NUnit v3.7.1 with TestDriven.NET so I can just right click into my Test file in Visual studio and say "Run Test(s)".

Sorry for this inconvenience guys but I think I just found where did I got wrong. Please see the attached files. I have really no intention of "duping" you, just wanted to help the community because I've been using NUnit for more than 3 years and it helped me a lot. Again guys, very sorry for this and thanks for all your expertise. Promise I will investigate further if ever I can find some undesirable output from my tests before posting an issue.

![no test](https://user-images.githubusercontent.com/29325852/27005692-28a946a0-4e56-11e7-84af-d802086aa002.PNG)
![with test](https://user-images.githubusercontent.com/29325852/27005691-289f3386-4e56-11e7-965a-723fb393ee3e.PNG)

**Comment by ayumsoftware** [comment]
One thing also, I did not intentionally commented out the "Test" attribute there. I really did not put it there to begin with because my tests sometimes passed. I do this with TestDriven.NET tool (and not putting "Test" attribute) whenever I am too lazy (or in a hurry) to test some miscellaneous tests. Very sorry again guys for taking some of your time. Won't to it again, promise :)

**Comment by jnm2** [comment]
My only recommendation is to never post an issue (in anyone's bug tracker) without doing a few searches to see what's already there, but certainly don't feel bad about being stumped! It happens to me all the time. 👍 

TestDriven.NET is misleading people though, not sure I like that.

**Comment by CharliePoole** [comment]
Hey @ayumsoftware 
You probably figured it out by now, but "dupe" isn't related to the english verb "to dupe" meaning to trick someone, it's short for "duplicate". It turns out your issue isn't a duplicate, however. 😄

**Comment by CharliePoole** [comment]
@jcansdale I think this may be a bug for you - unless it's an insufficiently explained feature. 😸 

According to @ayumsoftware it's possible to run a test without test attribute (or commented out) by clicking on it in TD.Net. If that's correct, I think it's an error on your part.

One guess I can make: are you recognizing tests by the legacy method - that they end in "Test"? NUnit has not done that for a long time.

In the past, it was possible to run any method, pretending it's a test, even if NUnit didn't see it as one. The assertion exception would show up as an error and give a reasonable approximation of the message you get on test failure. But that's no longer possible because Assert depends on the fact that it's running under a TestExecutionContext. In the past, we would set one up on the fly, but creating a completely disconnected, uninitialized context led to very hard to understand failures, so we stopped doing it.

**Comment by CharliePoole** [comment]
@ayumsoftware See... you did a good thing here! 😃

**Comment by ayumsoftware** [comment]
Hello @CharliePoole & @jnm2. Thanks guys for the effort of explaining these things to me. I feel ashamed because you ought not to do much effort about the issue that I submitted after finding out that it was my mistake. Don't worry, I already uninstalled the TestDriven.NET and use the TestRunners provided by NUnit. @jnm2 is pretty much convincing there which made me decide to use NUnit and its TestRunners. Sorry for stealing some of your time. Now, off I go :)

**Comment by jnm2** [comment]
@ayumsoftware It's really not a big deal. You're cool! Please stick around :smile:

**Comment by rprouse** [comment]
@ayumsoftware TD.NET is also a great tool, you just need to remember to add the Test attribute 😄

**Comment by jcansdale** [comment]
Hi folks!

The explanation is that the method is being executed as an "ad hoc" test. You can do this with pretty much any method, property or field. See here:
http://testdriven.net/quickstart.aspx#Ad%20Hoc%20Tests

The clue in this case is at the bottom in brackets where it shows the test runner used to execute the test.
![image](https://user-images.githubusercontent.com/11719160/27053790-80951162-4fb6-11e7-8ca0-de0cbd2e28fb.png)

If you're a VS extension developer you can also execute methods inside the running VS process using `Test With > In-Proc (VS SDK)`. You can pass any VS service interface or MEF export type (thought this might be of interested to @rprouse). See https://github.com/jcansdale/TestDriven.Net-Issues/issues/90 (grab the latest 4.1 Alpha)

Anyway, sorry about the confusion!

**Comment by jnm2** [comment]
That seems reasonable. What if we were to prevent the NRE and throw a more helpful exception explaining that NUnit tests can't be run ad-hoc?

**Comment by CharliePoole** [comment]
@jnm2 Who is "we" in this context? Jamie's code or ours?

And as far as R# goes, we're all in the dark.

NUnit has no concept of "adhoc" execution. It's an error if a test is run outside of an execution context. Even if we "knew" there was such a thing as TD.Net's adhoc execution, we can't just assume that's what is happening when there is no execution context - that can signal serious problems.

I think TD.Net has to trick NUnit into working correctly. The best way to prevent an NRE is for the client to provide a non-null execution context. @jcansdale If you are willing to provide me a copy of the code where you run us adhoc (offline that is), I'd be happy to suggest an approach.

**Comment by jnm2** [comment]
@CharliePoole Our code. I would say in general NRE is never a good thing to allow to escape when people misuse your framework. It sends the message "we have a bug we don't know about." We should provide a message with all the information necessary for people to figure out what is going on.

ReSharper is kind of irrelevant. If Visual Studio supported a quick action to start debugging from any static Main method, it'd still write one to debug my test on F5 over and over.

**Comment by CharliePoole** [comment]
@jnm2 It's generally a good principle not to allow exceptions to escape, but it's an equally important principal not to handle exceptions when you don't understand their cause. This particular exception, if it occurs when calling NUnit through our supported APIs is an internal error. Since we could only handle it by throwing some sort of InternalErrorException, we have never done so. When it comes up, we try to solve it as a high-priority bug, because __our code__ should never do this.

We have no idea of how Jamie calls us for this "adhoc" execution. If he tells us he is calling a supported API, then it will be our bug to fix. If he isn't then it's more his problem. We just don't know enough right now to have an opinion on how this should be fixed. 

This question comes up all the time when somebody calls into the framework from another program. Folks who do that are not "users" in the normal sense and we have to deal with them in a slightly different way. Folks like Jamie, with third-party runners, are pretty aware of this.

**Comment by jnm2** [comment]
@CharliePoole I agree with that, *if* TestDriven.NET is calling an NUnit API to run the method at all. But it's not. No runner is calling into NUnit; it's just running the code the user told it to. I think this should not result in an NRE but rather in a message explaining what's wrong:

```c#
public static class Program
{
    public static void Main() => new TheFixture().TheTest();
}

[TestFixture]
public sealed class TheFixture
{
    [Test]
    public void TheTest() => Assert.That(...);
}
```

**Comment by CharliePoole** [comment]
@jnm2 TD.Net is commercial, non-open code, so how do you know what it's doing? I don't.

**Comment by CharliePoole** [comment]
@jnm2 Taking it a step further: I _could_ try to do some reverse engineering, but I kind of think I shouldn't. 😺

**Comment by jnm2** [comment]
@CharliePoole IMO it doesn't matter what TD.NET is doing because we know that [this code sample](https://github.com/nunit/nunit/issues/2238#issuecomment-307951896) causes NUnit to surface a NRE without any third-party tools in the picture. Then, if we still have this issue with TD.NET which I doubt, it's a bug for jcansdale.

**Comment by CharliePoole** [comment]
@jnm2 Sorry... I didn't actually notice what your sample was doing. We shouldn't keep talking about this in the TD.NET issue, 'cause it confuses us old folks.

That has never been something users were __supposed__ to do, but I have certainly seen it before. It would have appeared to work for some percentage of tests in the past. I could argue that throwing an NRE is actually an improvement over false results -- but what you are asking for is even better.

Would you file an issue on this? Then, how about a PR? 😸 

I'm not sure off the bat how we would distinguish this case. I'm fairly certain that the non-existence of a TestExecutionContext isn't a sufficient test. But maybe we could give some sort of generic message that works for __either__ case: directly calling the test or an internal error by the nunit programmers.

**Comment by jnm2** [comment]
https://github.com/nunit/nunit/issues/2242
