### ISSUE TITLE
Retry attribute should handle unexpected exceptions

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2785]
Most users that use the `Retry` attribute do so because the code under test is flaky. More often than not, that code will throw an unexpected exception rather than returning incorrect data, but the Retry attribute only retries on assertion failures, not on errors. The retry should retry both.

See https://stackoverflow.com/questions/49520854/remove-failure-message-from-multiple-assertion-failure-in-nunit/49534616?noredirect=1#comment86075785_49534616 and https://testingrepository.com/retry-failed-tests-in-nunit/

**Comment by ChrisMaddock** [comment]
This has come up many times before! 😄 Although it's a change in behaviour, I agree it would be a good change to make.

Ref: https://github.com/nunit/nunit/issues/1388

**Comment by jnm2** [comment]
Since people keep asking for it, it seems like there should be a mode that is easier to apply than wrapping every method with `Throws.Nothing`.

**Comment by CharliePoole** [comment]
If you have to wrap __every__ method with `Throws.Nothing` you've really got a problem. This is really very much analogous to `ExpectedExceptionAttribute`, which suffered from the problem that the exception could occur __anyplace__ in the test. Here, it's somwhat worse since __any kind of exception__ is allowed anyplace in the test!

IMO, we need to offer a better solution that just retrying every test that produces an error.

**Comment by jnm2** [comment]
Yes, good to consider. https://github.com/nunit/nunit/issues/1388#issuecomment-350619200 asks for the ability to consider certain exception types as retriable across a very large number of test methods.

**Comment by CharliePoole** [comment]
Isn't this a duplicate of #1388, which we already accepted?

**Comment by rprouse** [comment]
Yes it is nearly a duplicate, that is the problem with having 241 open issues, it is sometimes hard to remember what is outstanding 😕 

While I agree that users could wrap suspect code in a `Throws.Nothing`, it makes it hard to assign values to variables which must be declared outside of the block and in some cases may be needed on several calls. Personally, I find `Retry` to be a code smell in itself, but the reality is that legacy systems can be flaky and hard to test, especially when networks are involved. If we can make that easier, it might prevent users from coming up with hard to support workarounds like those in the links I provided. I found it interesting how many people commented on that blog post. It means that many people have the same problem.

Maybe the solution is better documentation on how to deal with things like this? There is no reason that a `Throws.Nothing` cannot be a multi-statement lambda.

**Comment by CharliePoole** [comment]
It's easy to see how you could get confused. The issues about the same topic seem to keep proliferating. Looking at #1388, I see it's still marked as an idea for discussion. However, I thought we decided what to do about the RetryAttribute in #2543. One possibility is that we stop marking things for discussion without appointing some sort of discussion facilitator to get it through. However, I think we actually intended #1388 as an action item to implement a property setting that would treat exceptions as failures for the sake of retrying.

**Comment by rprouse** [comment]
Interestingly, the solution presented on https://testingrepository.com/retry-failed-tests-in-nunit/ is even wider in scope to this, it retries failed children, setup, teardown, etc.

```C#
while (count-- > 0)
{
	context.CurrentResult = innerCommand.Execute(context);
	var results = context.CurrentResult.ResultState;

	if (results != ResultState.Error
		&& results != ResultState.Failure
		&& results != ResultState.SetUpError 
		&& results != ResultState.SetUpFailure
		&& results != ResultState.TearDownError
		&& results != ResultState.ChildFailure)
	{
		break;
	}
}
```

**Comment by CharliePoole** [comment]
Some of these can't actually occur, but the author probably was unsure. The entire check should probably change to look at status plus label. failure can't occur. The others should probably be discussed but seem reasonable on the surface.

**Comment by siburny** [comment]
We too need to have ability to retry flaky tests.

This would be ideal in my case (and would not introduce a breaking change since RetryOnException would be false by default):
```
[Test, Retry(3, RetryOnException = true)]
public void Login()
{
    step.BasicActions.LoginAndOpenPart15038(_driver);
    Assert.True(false == _driver.Url.Contains("login.html"));
}
```

Or if we want to explicitly specify which exception to retry on we could specify it as a parameter.

**Comment by siburny** [comment]
I looked around the code, and it seems that exception type is not stored in the `ExceptionResult` structure. It needs to be stored first and then analyzed later.

**Comment by nyghtly-derek** [comment]
@siburny Any chance I could get a status update on that? I also have a need to retry flaky tests. I'm currently considering a workaround: https://stackoverflow.com/questions/54806393/retry-in-nunit-not-working-when-test-times-out

For the sake of posterity, I also wanted to make a quick argument against this statement: "If the code under test is just plain flaky, then it's supposed to fail."

In fact, I feel that there are many legitimate cases in which ignoring flakiness is valuable. For example: 

1. Flakiness only occurs in test environment because of limited compute power. Retrying is better than buying more compute for test.
2. Users report that the application is smooth, despite known flakiness. Retrying is better than always assuming test failures are because of known flakiness that we've chosen to accept. Test suite is more actionable because of this strategy.
3. Flakiness is caused by external library that cannot be removed at this time. Retrying is better than tests reporting flakiness that we cannot change.

And even if you disagree with every single one of these scenarios, it's worth remembering that testing for flakiness is not zero sum. It's trivial to duplicate the same test, and to configure only one of them to retry. This way, you have results to communicate both: (1) Is there a failing assert, and (2) is there flakiness?
 
LoginTest
LoginIsNotFlakyTest

**Comment by siburny** [comment]
All my changes are here: https://github.com/siburny/nunit/commit/24accb56c2519c1a98b74d1d291831086e0f4f2a

**Comment by stevenaw** [comment]
@nunit/framework-team 

I've discovered that this can be a pain point with third-party assertion or mocking libraries. In many cases authors will try not to take a hard dependencies on a particular version of any test framework (ex: NUnit, xunit, MSTest, etc) in order to support as many as possible. In these cases the libraries will rely on NUnit's (or others') handling of uncaught exceptions to communicate assertion failure and test failure.

I think this means that any tests which rely _exclusively_ on third-party assertion libraries will not be able to use `Retry` as the thrown exception will not cause the test to be retried.

**Comment by CharliePoole** [comment]
Using NUnit by itself (no 3rd party lib), the problem is readily resolved by transforming the error (exception) into a test failure..

```
Assert.That(() => /* Your code */), Throws.Nothing);
```

If that doesn't suffice with some library, an example would be useful. However, my view has always been that libraries intending to extend NUnit ought to be based on an understanding of how NUnit actually works, i.e. that it has not communicated failures via an exception for many years and now only uses the exception for the purpose of terminating test execution without continuing to the end of the test method.

This isn't to say I'm against any kind of change here. But the argument that people may want to use some third-party library _exclusively_ doesn't strike me as a good reason to make a change. Anyway, they're already using NUnit attributes, aren't they?

**Comment by stevenaw** [comment]
@CharliePoole 
Good point about examples. I will try to cobble a few together in an easy repro project. The particular case I hit for this earlier today was Moq's `Verify()` function, though I believe Shouldly and FluentAssertions behave similarly.

And FWIW I agree with you (from what I can surmise). I see this as a library relying on NUnit's behavior to fail a test when any exception is uncaught (at least that's how it still "seems" when watching a test execute in a runner). The RetryAttribute's behavior is a nuance that, for reasons described above, behaves differently in that failures due to uncaught exceptions are not retried. I agree with the comparison above to `ExpectedException` and that changing the default behavior here would be a trade-off that also makes it easier to write less focused and more unreliable tests.

I thought it could be helpful to point out the additional use case of third party assertion libraries. I hadn't seen that touched on yet in the discussion. The workaround to the assertion library issue is just to use a try/catch with an `Assert.Fail()` in the catch handler.

**Comment by stevenaw** [comment]
Perhaps any change here, if made at all, is best as an opt-in via a new property on the attribute? The RetryAttribute can only be set at method-level and so "relaxing" this particular behavior would also be only be opted into on a case-by-case basis. 

I'm still not really leaning one way or another on this myself, just brainstorming.

**Comment by CharliePoole** [comment]
As an old-timer, I'm very conscious of the strong distinction NUnit has always made between Failures and Errors. Users haven't always paid attention to this but it was considered very important at the beginning because the likely cause of a Failure was seen to be a problem in the system under test, while an error was usually caused by a problem in the test itself. Once  we started stretching the Test concept to allow more than micro-testing, their were many more sources of problems.

IMO it's too bad we allowed that to happen rather than conceptualizing an entirely different implementation for tests that went beyond straight unit testing. We once talked about a SystemTest, although other names would be more suitable today. Of course you can make the Test/TestCase/TestFixture hierarchy do more than one thing, but only at the expense of lots of options and alternative code paths, which makes it less robust.

That said, if we accept that the "SystemTest" ship has sailed, then a cleanly specified addition to the attribute arguments for Retry would probably do the job for Shouldly, etc. IMO, requiring specification of an exception type or types would promote better test writing and those who insist on complete generality could always use "Exception."

For mocking frameworks, however, I have always found it cleaner to just write a custom assertion that wraps Verify or its equivalent and actually causes a failure.

Speaking as a user these days, of course... :-) but it would be nice to put this to bed once and for all.

**Comment by manfred-brands** [comment]
I have created a PR for the suggested syntax:
```csharp
[Retry(3, typeof(TimeoutException), typeof(OperationCanceledException))]
```

**Comment by manfred-brands** [comment]
I removed the _breaking change_ label as this is an opt-in approach.
