### ISSUE TITLE
Some unit tests fail if the contributor's set culture isn't english

### ISSUE THREAD

**Issue by Augure34** [nunit/nunit#3388]
When running build.ps1 -t Test, the following output describes the failing tests:

> 1) Failed : NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite
  Expected: String containing "The system cannot find the file specified."
  But was:  "Le fichier sp├®cifi├® est introuvable. (Exception from HRESULT: 0x80070002)"
   at NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite() in D:\repos\Open Source\nunit\src\NUnitFramework\tests\Api\**FrameworkControllerTests.cs:line 373**

> 2) Failed : NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite
  Expected: String containing "The system cannot find the file specified."
  But was:  "Le fichier sp├®cifi├® est introuvable. (Exception from HRESULT: 0x80070002)"
   at NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite() in D:\repos\Open Source\nunit\src\NUnitFramework\tests\Api\**FrameworkControllerTests.cs:line 281**

> 3) Failed : NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite
  Expected: String containing "The system cannot find the file specified."
  But was:  "Le fichier sp├®cifi├® est introuvable. (Exception from HRESULT: 0x80070002)"
   at NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite() in D:\repos\Open Source\nunit\src\NUnitFramework\tests\Api\**FrameworkControllerTests.cs:line 484**

> 4) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite
  Expected: String starting with "The system cannot find the file specified."
  But was:  "Le fichier sp├®cifi├® est introuvable. (Exception from HRESULT: 0x80070002)"
   at NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite() in D:\repos\Open Source\nunit\src\NUnitFramework\tests\Api\**TestAssemblyRunnerTests.cs:line 122**

> 5) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite
  Expected: String starting with "The system cannot find the file specified."
  But was:  "Le fichier sp├®cifi├® est introuvable. (Exception from HRESULT: 0x80070002)"
   at NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite() in D:\repos\Open Source\nunit\src\NUnitFramework\tests\Api\**TestAssemblyRunnerTests.cs:line 313**

> 6) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite
  Expected: String starting with "The system cannot find the file specified."
  But was:  "Le fichier sp├®cifi├® est introuvable. (Exception from HRESULT: 0x80070002)"
   at NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite() in D:\repos\Open Source\nunit\src\NUnitFramework\tests\Api\**TestAssemblyRunnerTests.cs:line 429**

Those tests compare localized error messages with hardcoded english strings. They should really should base the result on the exception code instead.

**Comment by CharliePoole** [comment]
Good catch!

**Comment by Augure34** [comment]
I can work on this. I'm thinking turning this:
`Assert.That(GetSkipReason(result), Contains.Substring("The system cannot find the file specified."));`
Into this
`Assert.That(GetSkipReason(result), Contains.Substring(MISSING_FILE_EXCEPTION_CODE));`
(where MISSING_FILE_EXCEPTION_CODE = "0x80070002")
should be resilient enough no?

**Comment by mikkelbu** [comment]
@Augure34 Actually, looking more into this I'm surprised that the tests in `TestAssemblyRunnerTests `fail, as e.g. `Load_FileNotFound_ReturnsNonRunnableSuite` is decorated with an `SetUICulture("en-US")` attribute, so the test should only be executed with en-US local. I'll have to examine this in more detail. Are the tests failing for all environments or is it only for e.g. dotnetcore/.netframework?

For the other tests I think we should just solve them similar to how `Load_FileNotFound_ReturnsNonRunnableSuite` was solved in nunit/nunit#2895

**Comment by Augure34** [comment]
@mikkelbu The culture is the same in both .net framework and .net core. However the assert are sometimes different depending on the environment and don't always compare localized string. 
Removing those preprocessors still fail the tests and shows localized error messages:

> Expected: String containing "The system cannot find the file specified."
      But was:  "Impossible de charger le fichier ou l'assembly 'junk.dll' ou une de ses dépendances. Le fichier spécifié est introuvable.
      ----> Le fichier spécifié est introuvable. (Exception de HRESULT : 0x80070002)"

**Comment by LeeMartin77** [comment]
Thought I'd take a look at this, but I suspect this issue was fixed in changes removing netcore1.1 code: 

a5adf028c101283beecad0b49104468efe75b90f 

If you check the tests in question from the original issue, the hardcoded, language specific strings have now been deleted.

**Comment by mikkelbu** [comment]
Thanks for taking a look at this @LeeMartin77.

We still compare against `"Could not load"` in `TestAssemblyRunnerTests`, but I think this is fine as this message is created by us and not by the underlying runtime. I'll close this issue - and if the issue reappear then we can create a new one or reopen this one.
