### ISSUE TITLE
Exception when using test filters from .runsettings or --filter argument from dotnet test

### ISSUE THREAD

**Issue by thomasbiel** [nunit/nunit#4589]
NUnit 4.0.1
NUnit3TestAdapter  4.5.0
dotnet 6.0 / windows 11
running tests from command line via "dotnet test"

when using a test filter like
`(cat != UsesNetwork) and (cat != LongRunning)`
in .runsettings file or via --filter argument for dotnet this exception occurs:

Exception NUnit.Engine.NUnitEngineException,    Exception thrown executing tests in [...].dll
An exception occurred in the driver while counting test cases.
   at NUnit.Engine.Runners.DirectTestRunner.CountTestCases(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Run(ITestEventListener listener, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 108
   at NUnit.VisualStudio.TestAdapter.Execution.Run(TestFilter filter, DiscoveryConverter discovery, NUnit3TestExecutor nUnit3TestExecutor) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\Execution.cs:line 51
   at NUnit.VisualStudio.TestAdapter.VsTestExecution.Run(TestFilter filter, DiscoveryConverter discovery, NUnit3TestExecutor nUnit3TestExecutor) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\Execution.cs:line 154
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 295
InnerException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index was out or range of valida values (Parameter 'index')
Actual value was 0.
   at NUnit.Framework.Interfaces.TNode.NodeList.ThrowArgumentOutOfRangeException(Int32 index)
   at NUnit.Framework.Interfaces.TNode.get_FirstChild()
   at NUnit.Framework.Internal.TestFilter.FromXml(TNode node)
   at NUnit.Framework.Internal.TestFilter.GetChildNodeFilters(TNode node)
   at NUnit.Framework.Internal.TestFilter.FromXml(TNode node)
   at NUnit.Framework.Internal.TestFilter.FromXml(String xmlText)
   at NUnit.Framework.Api.FrameworkController.CountTests(String filter)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.ExecuteMethod(MethodInfo method, Object[] args)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.ExecuteMethod(String methodName, Object[] args)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.CountTestCases(String filter)
   at NUnit.Engine.Runners.DirectTestRunner.CountTestCases(TestFilter filter)

**Comment by thomasbiel** [comment]
Is the filter XML you dumped as expected? I would like to contribute if I can, maybe you can give a hint where to start.

**Comment by OsirisTerje** [comment]
Yes, the filter is as expected. 

You have to debug the framework.  You can either use NUnitLite as the runner, and set up the same filter there, or you can create a new sln with both the framework and the adapter and set the adapter for debugging.  The command for that is  here: https://docs.nunit.org/articles/vs-test-adapter/Debugging.html

**Comment by thomasbiel** [comment]
first analysis shows that TNode.FromXml produces an invalid output for the XML you dumped:
![grafik](https://github.com/nunit/nunit/assets/16876724/da934356-e1b7-4b97-8ff7-c5fa378ed46d)

**Comment by BrightLight** [comment]
We tried to update from NUnit 3.16.0 to 4.0.1 today and encountered the same problem.

> everything works fine until there is a test marked with [Explicit] along with non-marked tests in a fixture.

The exception happens also if there is a whole fixture that is marked as `[Explicit]`.
I checked our project for use of `[Explicit]` and found two locations. One was on a test method within within a fixture (which had other, non-explicit tests). The other location was on a fixture itself.

```csharp
[TestFixture]
public sealed class Foo
{
  [Test]
  public void Test1()  { }

  [Test]
  [Explicit]
  public void Test2()  { }
}

[Explicit]
public sealed class Bar
{
  [Test]
  public void Test1()  { }
}
```

I had to remove both to get rid of the exception.

**Comment by OsirisTerje** [comment]
@BrightLight 3.16 ?  There is no NUNit 3.16.  Do you mean the console ?

**Comment by BrightLight** [comment]
@OsirisTerje I'm sorry. I meant NUnit 3.14.0. And NUnit3TestAdapter 4.5.0.

**Comment by OsirisTerje** [comment]
@BrightLight  Without any filters, it works as it should, ref https://github.com/nunit/nunit.issues/tree/main/Issue4589  
![image](https://github.com/nunit/nunit/assets/203432/5ea48d04-5ffe-4251-8376-8b51bb53b65c)

What kind of filters do you use?  In VS or on cmd line with dotnet test ?

**Comment by BrightLight** [comment]
@OsirisTerje we use `dotnet test`. This is the command line from our build job:
```
dotnet test %PROJECT_HOME_NET%\bin\%OUTDIR%\net6.0-windows\MyAssemblyTests.dll --filter "TestCategory!=Benchmark & TestCategory!=DbSchemaDependent & TestCategory!=Integration & TestCategory!=UI" --blame-hang-timeout 10min --logger "trx;LogFilePrefix=NUnit-net6.0-windows" --results-directory "%PROJECT_HOME_NET%\bin\%OUTDIR%" 
```

This particular project defines 3854 tests. The tests of the two fixtures where `[Explicit]` is used don't define a [Category] attribute, that's why I didn't add it to my example code. But there's one testfixture in the project that uses the "Integration" category (which therefore is excluded by the command line filter). But this fixture is not the one that has `[Explicit]` tests.

Sorry if I caused confusion. I just wanted to underline that we can reproduce the originally described issue, but also that the issue also occurs if whole fixtures are marked as explicit and the project has (other) tests which are excluded by a filter.

**Comment by OsirisTerje** [comment]
@thomasbiel Have you had any success in debugging this further?

**Comment by thomasbiel** [comment]
No, before doing anything I need an answer to my question from https://github.com/nunit/nunit/issues/4589#issuecomment-1880096091

**Comment by OsirisTerje** [comment]
Sorry, I missed that question.
The (1) looks wrong.  The second looks more correct, but given we can have also have `or` statements, it might be an outer `and` that is missing ?

**Comment by miky-quadient** [comment]
We have also encountered this problem in two projects. I tried removing the use of the explicit attribute as a workaround. In one project it helped, in the other it didn't.

**Comment by OsirisTerje** [comment]
@miky-quadient What are your filter statements?

**Comment by miky-quadient** [comment]
@OsirisTerje 
dotnet test Packages.sln --filter TestCategory!=LinuxUnstable&TestCategory!=AzureEmulator&TestCategory!=DevopsUnstable

**Comment by maedula** [comment]
Same here. We want to transition our project to net8.0 and upgraded to NUnit v4 but are blocked by this bug. So we would also greatly appreciate a bugfix for this issue.

**Comment by thomasbiel** [comment]
@maedula upgrading to net8 only requires the update of NUnitTestAdapter, which works fine with NUnit 3.4, although this is (as in my case) not the preferred solution.
Another workaround is to create your own ExplicitAttribute with the least nested namespace shared with all your test classes, so it gets found before NUnit.Framework.ExplicitAttribute, e.g.
```
using System;
using NUnit.Framework;

namespace YourOwnNamespace; 

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Assembly, AllowMultiple = true)]
public class ExplicitAttribute : CategoryAttribute
{
    public ExplicitAttribute(string description = null) : base(Category) { }

    public const string Category = "Explicit";
}
```

That allows filtering explicit tests via category.

**Comment by stevenaw** [comment]
@OsirisTerje Does this look similar to #3979 to you given the interplay with `Explicit`?

If so I'm wondering if we should close #3979 given this issue has momentum

**Comment by OsirisTerje** [comment]
@stevenaw Yes.  Makes sense .

**Comment by stevenaw** [comment]
Done!

**Comment by mbenedykconfigit** [comment]
Are there any updates regarding to this issue? Will it be fixed?

**Comment by OsirisTerje** [comment]
@mbenedykconfigit Yes it will be fixed.

**Comment by SamWilliamsGS** [comment]
We're still seeing this problem on .NET 8 with NUnit 4.1.0. Is a fix on the roadmap? 🙂

**Comment by mbenedykconfigit** [comment]
can we have an update on it?

**Comment by OsirisTerje** [comment]
@thomasbiel  Any chance of progress on this one?

**Comment by stevenaw** [comment]
This has been fixed and should release as part of NUnit 4.2
