### ISSUE TITLE
NUnitLite fails with ArgumentException in AOT publish

### ISSUE THREAD

**Issue by vpenades** [nunit/nunit#4987]
using NUnit 4.3.2 and NUnitLite 4.3.2 , I am trying to create a console test that is run like this:

```c#
class Program
{
    static int Main(string[] args)
    {
        return new AutoRun(typeof(CustomTests).Assembly).Execute(args);   
    }
}
```

When I run the program in normal mode, the tests run just fine, but when I publish the console application and I try to run it, I get this output:

```
Runtime Environment
   OS Version: Microsoft Windows 10.0.19045
  CLR Version: 8.0.16

Test Files


System.ArgumentException: Argument name must not be the empty string (Parameter 'name')
   at NUnit.Framework.Guard.<ArgumentNotNullOrEmpty>g__ThrowArgumentNotNullOrEmpty|1_0(String) + 0x44
   at NUnit.Framework.Internal.Test..ctor(String, String, ITypeInfo, IMethodInfo) + 0x23
   at NUnit.Framework.Internal.TestSuite..ctor(String) + 0x53
   at NUnit.Framework.Internal.TestAssembly..ctor(String) + 0x17
   at NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(Assembly, String, IDictionary`2) + 0x500
   at NUnit.Framework.Api.NUnitTestAssemblyRunner.Load(Assembly, IDictionary`2) + 0xc8
   at NUnitLite.TextRunner.LoadTests(IDictionary`2) + 0x36
   at NUnitLite.TextRunner.Execute() + 0x359
```

I've tried several workarounds with no success. any ideas?

**Comment by OsirisTerje** [comment]
PublishAot bundles everything into a single native Exe, something NUnit don't expect.  It uses Assembly.Location but in the Aot case it is always an empty string since there are no dll anymore.  
That is what the guard catches.

We should fix this though.

**Comment by vpenades** [comment]
I've found that when Assembly.Location is not found, good candidate replacements are System.AppContext.BaseDirectory and System.Environment.ProcessPath  , maybe they could be used as fallbacks for when Assembly.Location is null

**Comment by stevenaw** [comment]
The underlying issue with `Assembly.Location` has been previously fixed (likely in https://github.com/nunit/nunit/pull/5024 though potentially also in https://github.com/nunit/nunit/pull/5308). A NativeAOT console app using NUnitLite can now _compile_ fine using the code snippet, though trimming compatibility issues remain. For this and other AOT-related efforts I have created https://github.com/nunit/nunit/issues/5358
